version: 1.0.{build}

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"
  
before_build:
- nuget restore

build:
  publish_nuget: true
  project: FluentNest.sln
 
test: off

deploy:
  provider: NuGet
  api_key:
    secure: lAGX1lk0eLBCOhFXhGLcn2Jr7ZGaa5mbLvMkJWAN0pmZ8P/vXeVbQd0WtvPHrruc
  skip_symbols: true
  artifact: /.*\.nupkg/