version: 1.0.{build}

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"
  
before_build:
- nuget restore

build:
  publish_nuget: true
  project: FluentNest.sln
 
test: off

deploy:
  provider: NuGet
  api_key:
    secure: 800c50e6-8f17-4ab9-8869-0993a102ff84
  skip_symbols: true
  artifact: /.*\.nupkg/